name: CI Color cone algorithm

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.7 & env vars
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      
      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1
      
      - name: Install dependencies
        run: |
          pipenv install --dev

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test with pytest
        run: |
          pipenv run pytest -x

