name: CI Color cone algorithm

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setting up Python 3.7 & env vars
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      
      - name: Pip Cache
        uses: actions/cache@v1
        id: pip-cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-3.7-${{ hashFiles('Pipfile.lock') }}-v3
          restore-keys: ${{ runner.os }}-pip-3.7-

      - name: Pipenv cache
        uses: actions/cache@v1
        id: pipenv-cache
        with:
          path: ~/.cache/pipenv
          key: ${{ runner.os }}-pipenv-3.7-${{ hashFiles('Pipfile.lock') }}-v3
          restore-keys: ${{ runner.os }}-pipenv-3.7-

      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1

      - name: Install dependencies
        if: steps.pipenv-cache.outputs.cache-hit != 'true'
        run: |
          pipenv install --dev

      - name: Testing with pytest
        run: |
          pipenv run pytest -x

