name: CI Color cone algorithm

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setting up Python 3.7 & env vars
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      
      - uses: dschep/install-pipenv-action@v1

      - name: Cache pipenv
        id: cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/pipenv
          key: ${{ runner.os }}-pipenv-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-
            
      - name: Install dependencies with pipenv
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          pipenv install --dev

      - name: Testing with pytest
        run: |
          pipenv run pytest -x

